// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sp_runif
arma::sp_mat sp_runif(int nrows, int ncols, double d);
RcppExport SEXP arma64bit_sp_runif(SEXP nrowsSEXP, SEXP ncolsSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type ncols(ncolsSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    __result = Rcpp::wrap(sp_runif(nrows, ncols, d));
    return __result;
END_RCPP
}
// sp_copy
arma::sp_mat sp_copy(arma::sp_mat& mat);
RcppExport SEXP arma64bit_sp_copy(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type mat(matSEXP);
    __result = Rcpp::wrap(sp_copy(mat));
    return __result;
END_RCPP
}
