# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate random uniform matrix using armadillo
#' @param nrows Integer scalar. Number of rows.
#' @param ncols Integer scalar. Number of columns.
#' @param d Numeric scalar. Density.
#' @export
sp_runif <- function(nrows, ncols, d) {
    .Call('arma64bit_sp_runif', PACKAGE = 'arma64bit', nrows, ncols, d)
}

#' Copy a matrix using armadillo's iterators
#' @param mat dgCMatrix. Matrix to copy.
#' @export
sp_copy <- function(mat) {
    .Call('arma64bit_sp_copy', PACKAGE = 'arma64bit', mat)
}

